version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI='mongodb+srv://farhanmukit0:LnBsfo2rFTk0OSFF@cluster0.otbjk4d.mongodb.net/recipeapp'
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: